[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36.2", features = ["tokio"] }
tokio = { version = "1.38.0", features = ["full"] }
anyhow = { version = "1.0.86" }
env_logger = "0.11.3"
log = "0.4.22"